---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: acm-sub
    spec:
      selector:
        matchLabels:
          app: acm-sub
        #explore if one can use a match experession for any label "subscription" matching "*-acm-sub"
