
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: dev-acm-sub

bases:
- ../subscription

commonLabels:
  app: dev-acm-sub

patches:
- patch: |-
    - op: replace
      path: /metadata/annotations/apps.open-cluster-management.io~1git-path
      value: "managed-subscription/dev"
    - op: replace
      path: /metadata/annotations/apps.open-cluster-management.io~1git-branch
      value: development
  target:
    group: "apps.open-cluster-management.io"
    kind: Subscription
    name: acm-sub
- patch: |-
    - op: replace
      path: /spec/selector/matchLabels/app
      value: dev-acm-sub
  target:
    group: "app.k8s.io"
    kind: Application
    name: acm-sub

namePrefix: dev-
# we need to also change the reference to those names this
# requires additional config for kustomize to recognise those 
# references in placementBinding this iscontrolled 
# through configurations.
configurations:
  - nameReference.yaml
