kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'sandpit-subscription-owner:global-edit'
subjects:
  - kind: ServiceAccount
    name: sandpit-subscription-owner
    namespace: sandpit-local-acm-subscription
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
