kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin'
subjects:
  - kind: User
    name: kube:admin
  - kind: User
    name: system:admin
  - kind: User
    name: system:serviceaccount:production-acm-sub:production-subscription-owner
  - kind: User
    name: system:serviceaccount:preprod-acm-sub:preprod-subscription-owner
  - kind: User
    name: system:serviceaccount:dev-acm-sub:dev-subscription-owner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
