
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: sandpit-local-acm-subscription

bases:
- ../subscription

commonLabels:
  app: sandpit-local-acm-subscription

patches:
- patch: |-
    - op: replace
      path: /metadata/annotations/apps.open-cluster-management.io~1git-path
      value: "managed-subscription/sandpit"
    - op: replace
      path: /metadata/annotations/apps.open-cluster-management.io~1git-branch
      value: sandpit
  target:
    group: "apps.open-cluster-management.io"
    kind: Subscription
    name: local-acm-subscription
- patch: |-
    - op: replace
      path: /spec/selector/matchLabels/app
      value: sandpit-local-acm-subscription
  target:
    group: "app.k8s.io"
    kind: Application
    name: local-acm-subscription

namePrefix: sandpit-
# we need to also change the reference to those names this
# requires additional config for kustomize to recognise those 
# references in placementBinding this iscontrolled 
# through configurations.
configurations:
  - nameReference.yaml
