
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sandpit-local-acm-subscription

bases:
- ../applications
- ../config
- ../policies


commonLabels:
  subscription: sandpit-local-acm-subscription

patches:
- patch: |-
    - op: replace
      path: /metadata/annotations/apps.open-cluster-management.io~1git-branch
      value: sandpit
  target:
    group: "apps.open-cluster-management.io"
    kind: Subscription

namePrefix: sandpit-
# we need to also change the reference to those names this
# requires additional config for kustomize to recognise those 
# references in placementBinding this iscontrolled 
# through configurations.
configurations:
  - nameReference.yaml
